[tool.poetry]
name = "accumulated-local-effect"
version = "0.9.0"
description = ""
authors = ["AI Verify"]
readme = "README.md"
packages = [{include = "accumulated_local_effect"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
numpy = "1.23.5"
pandas = "1.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
