site_name: AI Verify User Guide
site_url: https://imda-btg.github.io/aiverify/

dev_addr: 0.0.0.0:8001 #setup as port 8001 so as not to clash with developer docs (TESTING)

copyright: |
  &copy; 2023 AI Verify</a>

extra_css:
  - stylesheets/extra.css

theme:
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top

  name: "material"
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - tables

plugins:
  - mkdocs-jupyter:
      execute: False

nav:
  - Introduction:
      - Introduction: index.md
      - AIVT 2.0 Features: introduction/AIVT 2.0 features.md
  - Quick Start Guide: ./quick-start-guide.md
  - Getting Started: ./getting-started.md
  - Detailed Guide:
      - Installation using Kubernetes: ./detailed-guide/installation-using-kubernetes.md
      - Preparation of Input Files:
          - Introduction: ./detailed-guide/input-preparation/preparation-of-input-files.md
          - Prepare Tabular Datasets and models: ./detailed-guide/input-preparation/prepare-tabular.ipynb
          - Prepare Image Datasets and models: ./detailed-guide/input-preparation/prepare-image.ipynb
  
      - AI Verify Process checklists: ./detailed-guide/aiverify-process-checklist.md
      - Veritas Process checklists: ./detailed-guide/veritas-process-checklist.md
      - Plugin Management: ./detailed-guide/plugin-management.md
      - Fairness Test: ./detailed-guide/fairness-test.md
      - Explainability Test: ./detailed-guide/explainability-test.md
      - Robustness Test: ./detailed-guide/robustness-test.md
      - Supported Versions: ./detailed-guide/supported-versions.md
      
  - FAQs: others/faq.md
  - Appendix: 
      - Standalone model vs Model pipeline: ./appendix/standalone-vs-pipeline.md
      - Understand the Fairness Decision Tree: ./appendix/use-fairness-tree.md

  - References:
      - AI Verify Developer Tools: https://github.com/aiverify-foundation/aiverify-developer-tools/
  # - Developer Documentation: https://aiverify-foundation.github.io/aiverify-developer-tools/getting_started/start_here/
  # - Release Notes: TODO
  #     - License: test.md
  #     - Contact Information: test.md
