version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --include /etc/redis/redis.conf
    volumes:
       - ./redis-init/redis.conf:/etc/redis/redis.conf
#      - ./data/redis:/data
#      - ./logs/redis:/var/log/redis
    networks:
      - app-network

  db:
    image: mongo:6.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_ROOT_USER:-mongodb}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_ROOT_PASSWORD:-mongodb}'
      MONGO_INITDB_DATABASE: admin
      MONGO_AIVERIFY_PASSWORD: '${DB_AIVERIFY_PASSWORD:-aiverify}'
    user: '${CUR_UID}:${CUR_GID}'
    volumes:
      - ~/data/db:/data/db
      - ~/logs/db:/var/log/mongodb
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # backend - test-engine
  test-engine:
    image: aiverify:0.10
    restart: always
    depends_on:
      - redis
    working_dir: /app/aiverify/test-engine-app
    command: python3 -m test_engine_app
    volumes:
      - plugins-volume:/app/aiverify/ai-verify-portal/plugins
      - logs-volume:/app/aiverify/test-engine-app/logs
      - uploads-data-volume:/app/aiverify/uploads/data
      - uploads-model-volume:/app/aiverify/uploads/model
    networks:
      - app-network

  # frontend - portal & apigw
  portal:
    image: aiverify:0.10
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - redis
      - db
    working_dir: /app/aiverify/ai-verify-portal
    command: bash -c "cd ../ai-verify-apigw && node app.mjs & cd ../ai-verify-portal && npm run start"
    volumes:
      - plugins-volume:/app/aiverify/ai-verify-portal/plugins
      - logs-volume:/app/aiverify/test-engine-app/logs
      - uploads-data-volume:/app/aiverify/uploads/data
      - uploads-model-volume:/app/aiverify/uploads/model
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  plugins-volume:
  logs-volume:
  uploads-data-volume:
  uploads-model-volume:
