[tool.poetry]
name = "fairness-metrics-toolbox-for-classification"
version = "0.9.0"
description = ""
authors = ["AI Verify"]
readme = "README.md"
packages = [{include = "fairness_metrics_toolbox_for_classification"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
numpy = "1.23.5"
scikit-learn = "1.2.2"
scipy = "1.9.3"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
