[tool.poetry]
name = "shap-toolbox"
version = "0.9.0"
description = ""
authors = ["AI Verify"]
readme = "README.md"
packages = [{include = "shap_toolbox"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
joblib = "1.2.0"
numpy = "1.23.5"
pandas = "1.5.3"
scikit-learn = "1.2.2"
shap = "0.41.0"
setuptools = "^67.8.0"
xgboost = "1.7.4"
scipy = "1.9.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
