[tool.poetry]
name = "shap-toolbox"
version = "0.10.0"
description = ""
authors = ["AI Verify"]
readme = "README.md"
packages = [{include = "shap_toolbox"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
joblib = "1.3.2"
numpy = "1.24.3"
pandas = "2.2.0"
scikit-learn = "1.4.0"
setuptools = "69.0.3"
xgboost = "2.0.3"
scipy = "1.12.0"
shap = "0.44.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
