name: Publish Docs

on:
  push:
    branches: [ docs ]

  # Run this workflow manually from Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  publish-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: Checkout docs
        uses: actions/checkout@v3
        with:
          ssh-key: ${{secrets.DEPLOY_DOCS_KEY}}

      # Install dependencies (mkdocs)

      - name: Install mdkdocs
        run: |
          pip install mkdocs

      - name: Push to gh-pages
        run: |
          git config user.name "imda-btg"
          git config user.email "idma-btg@imda.gov.sg"
          git config pull.rebase true
          git pull origin gh-pages

          mkdocs gh-deploy --clean
